### ISSUE TITLE
Popup more_info not closing

### ISSUE THREAD

**Issue by jordaosoft** [thomasloven/hass-browser_mod#121]
I use a wall tablet to popup the front camera view when motion is detected at the door and leave it up for 2 minuets. 
The popup works fine but wont close the popup even when calling service browser_mod.close_popup from HA.

I use:
  service: browser_mod.more_info
  service_data:
    entity_id: camera.driveway
    deviceID:
      - 3b0e3ca9-9b6d5d01

It gives me the flowing error in chrome developer tools when calling the popup:
browser_mod.js:90 Uncaught TypeError: Cannot set property 'large' of undefined
    at p (browser_mod.js:90)
    at v.more_info (browser_mod.js:149)
    at v.callback (browser_mod.js:149)
    at Object.e.subscribeMessage.type [as callback] (browser_mod.js:149)
    at o._handleMessage (core.a99cac39.js:1)
    at WebSocket.<anonymous> (core.a99cac39.js:1)

There is no error when calling browser_mod.close_popup just nothing happens.

**Comment by kzim200** [comment]
I am having the same problem with my wall tablet. I am only able to close the popup by clicking the back button.
In fact, I am seeing similar results on my PC as well. 
Also, the popup is no longer centered.  It is appearing in the upper left corner on of the screen and the X to close it is actually on the screen behind the pop-up, not hidden, just behind it. 
![image](https://user-images.githubusercontent.com/20750976/88486080-6b849700-cf7b-11ea-87e1-3d45376b7bb7.png)

**Comment by thomasloven** [comment]
Use release 29 or earlier for Home Assistant 0.112 or earlier.

**Comment by kzim200** [comment]
Sorry, I thought I had updated, but apparently I had not.  
It is working perfectly now.

**Comment by rpitera** [comment]
Having same issue as @jordaosoft .  No error message, just doesn't close the more-info popup.  HA vers 0.113.1

**Comment by chasut** [comment]
Thank you for posting, having the same issue with my front door camera popup.  Spent an hour trying to figure out if the breaking change in scripts/automations was the culprit till I ran across this.

The message below is the only thing I see in the logs when it occurs. When my script is called I see this message three times; presumably one  each for the 3 browser_mod service calls.  One for the "close_popup call that precedes the camera, one for the more_info call for the camera popup, and one for the close_popup call after a delay.

2020-07-27 12:51:51 ERROR (MainThread) [frontend.js.latest.202007160] http://10.0.0.48:8123/browser_mod.js:90:9541 TypeError: undefined is not an object (evaluating 'i.large=t')

Interestingly, if I replicate these calls within the HA Dev Tools, I only get a single error (same one) for the browser_mod.more_info.  The browser_mod.close_popup service does not generate the error, and does not close the popup on my panel (iPad OS 13.6).  Not sure what that means, could be user error.

HA 0.113.1, BMOD 1.1.3

Thanks

**Comment by thomasloven** [comment]
This problem should be fixed in release 1.1.5

**Comment by rpitera** [comment]
@thomasloven - what settings do I use to set up debug on HA logs for browser_mod?  Something suddenly cropped up out of nowhere on 1.1.3 and it's not loading (which also seems to be blocking my default view).  I tried updating to 1.1.5 but it's still not loading.

**Comment by liveware-problems** [comment]
Upgraded to 1.1.5 however the popup is still not closing :( error still showing in HA logs:

Logger: frontend.js.latest.202007160
Source: components/system_log/__init__.py:209
First occurred: 9:28:57 AM (12 occurrences)
Last logged: 10:37:16 AM

https://redacted.duckdns.org/browser_mod.js:90:907 Uncaught TypeError: Cannot set property 'large' of undefined

**Comment by Oriondely** [comment]
Hi all,
my HA version is 0.100.2, I'm using release 29 because the newer onces don't work correctly with "older" HA version, but I have the "popup not closing" issue: the X is not shown. 
If I use back button on android devices it close HA and not only the popup. Will the next hass-browser_mod release compatible also with older version of HA ?

Thank you
