### ISSUE TITLE
browser_mod.lovelace_reload doesn't trigger lovelace reload/refresh

### ISSUE THREAD

**Issue by greberg** [thomasloven/hass-browser_mod#35]
Hi

Can't get browser_mod.lovelace_reload service to work. I have tried it from HA service menu as well as from an automation and can't get it to work. Just for my understanding, I assume that you don't give any service data to browser_mod.lovelace_reload like DeviceId or so.

Best regards Peter

**Comment by thomasloven** [comment]
Correct. Perhaps you misunderstand what it is supposed to do.

browser_mod.lovelace_reload does the same thing as clicking the three dots in the top right corner and select Refresh. It reloads the lovelace configuration from the server, but does not cause the browser to refresh the view (as with e.g. F5).

**Comment by igloo15** [comment]
is it possible to add a browser reload as F5? Some of the cameras feeds on my lovelace interface do not show up after HA is restarted unless I reload the webpage entirely. Would be nice to do that through this mod.

**Comment by Dino-Tech** [comment]
@igloo15  I have been using this `script` effectively for quite some time now:
```yaml
browser_navigate:
  sequence:
    - service: browser_mod.lovelace_reload
    - delay: '00:00:03'
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/0 #<-- or whatever view
```
works well with my mounted tablets.

**Comment by igloo15** [comment]
@Dino-Tech that works but I think I would have to do per device as each one has a different view

**Comment by Dino-Tech** [comment]
@igloo15  then use `deviceID` like this:
```yaml
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/0
        deviceID:
          - OfficePC
          - OfficeTab LAN
          - Kiosk
```

**Comment by igloo15** [comment]
@Dino-Tech I implemented your script today but unfortunately it didn't work. Navigating didn't do whatever refreshing the page does to make the camera picture-entities reconnect. 

I am going to try and mod this and see if I can add the reload function

**Comment by Dino-Tech** [comment]
@igloo15  Seems I remember I had one device that gave me issues. I had to navigate off the view> reload> then navigate back to the home view> reload again to get the proper refresh needed. Seems like a lot of unnecessary steps, but since the action was automated to fire the `script`, I only had to set it up once. My issue was originally screen loading/displaying and not camera related though. May not be what you are needing.

**Comment by igloo15** [comment]
@Dino-Tech I already tried the navigate somewhere else and then back again and it did not work. Regardless I modded the plugin in like 2 minutes and got the desired reload I was looking for.

If @thomasloven wants I can submit a pull request with the changes to add a page reload function. The steps to recreate are simple:

1. Locate browser_mod.js in the browser_mod plugin
2. Find the following piece of code in that file `case "lovelace-reload":{somestuff} break;`
3. After the `break;` insert this code `case "window-reload":window.location.reload(false);break;`
4. Find const.py file it should be in same folder as browser_mod.js
5. Insert in the USER_COMMANDS array the following string: `"window-reload",` doesn't matter where just insert it
6. Restart Home Assistant

If all worked correctly you should now have a service called browser_mod.window_reload. Calling this service will reload all the pages connected. You may have to hard refresh and clear cache of all clients connected to web browser so you can get the new browser_mod.js.

**Comment by gamer06** [comment]
@igloo15 This solution "window-reload" still working for you?
Thanks

**Comment by Dino-Tech** [comment]
@gamer06  yes it does, but I added the new service like this. Working well ATM, but loading frontend still buggy post `0.107.3` 
```yaml
browser_window_reload:
  sequence:
    - service: lovelace.reload_resources
    - delay: '00:00:10'
    - service: browser_mod.window_reload
      data:
        navigation_path: /lovelace/home
        deviceID:
          - OfficeTab LAN
          - Kiosk
          - mainKiosk
          - OfficePC
```
Anyone have a better solution, please post and thanks!

**Comment by gamer06** [comment]
> @gamer06 yes it does, but I added the new service like this. Working well ATM, but loading frontend still buggy post `0.107.3`
> 
> ```yaml
> browser_window_reload:
>   sequence:
>     - service: lovelace.reload_resources
>     - delay: '00:00:10'
>     - service: browser_mod.window_reload
>       data:
>         navigation_path: /lovelace/home
>         deviceID:
>           - OfficeTab LAN
>           - Kiosk
>           - mainKiosk
>           - OfficePC
> ```
> 
> Anyone have a better solution, please post and thanks!

@Dino-Tech i dont have "lovelace.reload_resources" in services...

**Comment by Dino-Tech** [comment]
you should, (I think) after `0.107.+` unless that's for `mode: yaml` only...IDK, but it popped up as soon as I updated to `0.107.1` However, the `window-reload` mod was working after latest update from dev service for me

**Comment by gamer06** [comment]
i'm in 0.107.4 and di havent the "lovelace.reload_resources. I will wait more updates to see if change. But the window-reload doesnt work for me too

**Comment by igloo15** [comment]
@gamer06 It is still working for me on 0.106.6. I have not upgraded to 0.107 yet. I do not reload lovelace as part of my automation. Instead on homeassistant start I reload the webpages. I have to do this because when I restart homeassistant the various video feeds I have on my monitors do not reload correctly. The below automation waits 15 seconds after homeassistant start and then reloads all the connected browsers. I also manually run the automation when I make lovelace changes but I manually hit the lovelace refresh usually.

```
id: 'Reload on startup'
  alias: Restart Browsers
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: '15'
  - data: {}
    service: browser_mod.window_reload
```

**Comment by igloo15** [comment]
@gamer06 I just updated to 0.107.4 and windows-reload is still working for me. I made a new script that accomplishes what I think you want to do and it works. I don't know what `lovelace.reload_resources` is but this works.

```
browser_reload:
  alias: Browser Reload
  sequence:
  - service: browser_mod.lovelace_reload
  - delay: 00:00:03
  - service: browser_mod.window_reload
```

**Comment by greberg** [comment]
> Correct. Perhaps you misunderstand what it is supposed to do.
> 
> browser_mod.lovelace_reload does the same thing as clicking the three dots in the top right corner and select Refresh. It reloads the lovelace configuration from the server, but does not cause the browser to refresh the view (as with e.g. F5).

Hi

No, from a cast perspective it doesn't behave the same way as the three dots refresh so I believe it should state that it behave the same way locally on your HA instance in description. Because I can't trigger refresh on the cast device using the browser_mod.lovelace_reload but if I choose "three dots -> refresh" my cast screen gets updated and refreshed.

For those that need to refresh the screen on a cast display from an automation just cast to another view and then cast back to the screen you want to display, then all custom ui components will be loaded as expected.

**Comment by Dino-Tech** [comment]
> I don't know what `lovelace.reload_resources` is but this works.

![image](https://user-images.githubusercontent.com/38272439/78292781-33010f00-74ed-11ea-9667-c1b9cfef093c.png)
Dev tools listed service: `lovelace.reload_resources` post `0.107.+` 
![image](https://user-images.githubusercontent.com/38272439/78293152-bc184600-74ed-11ea-9095-45e51540095e.png)
@igloo15

**Comment by gamer06** [comment]
Hello guys.

I already know why in my case (0.107.7) there is no "Reload_resources" and "Refresh" in lovelace. These 2 commands only work in yaml mode only. Bad for me...

@Dino-Tech Is it normal for me with a screensaver with a bigtimer card (popup card) on the tablet, when the tablet is on the screensaver she doesn't update the tablet screen? For example I have an icon that says "good morning or good afternoon" and that icon does not update when it is in the screensaver ...

**Comment by Dino-Tech** [comment]
@gamer06 That would probably be the state/refresh of the sensor/entity you are using for "good morning or good afternoon". My 2nd phase screensaver is a clock and current time is always displayed correctly without having to close/re-open the popup.

**Comment by gamer06** [comment]
Your 2nd phase screensaver is in your git?

**Comment by Dino-Tech** [comment]
@gamer06 Yes, : [here](https://github.com/Dino-Tech/Home-Assistant-Main/blob/master/scripts.yaml#L1117-L1145) 
The 1st phase is a random picture frame that runs for a while before the clock pops up, but I just added that and haven't put it on repo yet.

**Comment by SBado** [comment]
> @Dino-Tech I already tried the navigate somewhere else and then back again and it did not work. Regardless I modded the plugin in like 2 minutes and got the desired reload I was looking for.
> 
> If @thomasloven wants I can submit a pull request with the changes to add a page reload function. The steps to recreate are simple:
> 
> 1. Locate browser_mod.js in the browser_mod plugin
> 2. Find the following piece of code in that file `case "lovelace-reload":{somestuff} break;`
> 3. After the `break;` insert this code `case "window-reload":window.location.reload(false);break;`
> 4. Find const.py file it should be in same folder as browser_mod.js
> 5. Insert in the USER_COMMANDS array the following string: `"window-reload",` doesn't matter where just insert it
> 6. Restart Home Assistant
> 
> If all worked correctly you should now have a service called browser_mod.window_reload. Calling this service will reload all the pages connected. You may have to hard refresh and clear cache of all clients connected to web browser so you can get the new browser_mod.js.

Pull request [created](https://github.com/thomasloven/hass-browser_mod/pull/93), thank you.

**Comment by nibblerrick** [comment]
Thanks for creating that pullrequest, exactly what I need. Hopefully it gets merged.

**Comment by kquinsland** [comment]
> @Dino-Tech I implemented your script today but unfortunately it didn't work. Navigating didn't do whatever refreshing the page does to make the camera picture-entities reconnect.
> 
> I am going to try and mod this and see if I can add the reload function


@igloo15, I've had the same issue w/ Camera Entity cards and am currently looking for a way to trigger the 'refresh' of my tablets, too.

Please add a +1 to this bug: https://github.com/home-assistant/frontend/issues/4302

**Comment by thomasloven** [comment]
Fixed by #93
